#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0x495143D05D0712D1
#
Name     : autogen
Version  : 5.18.16
Release  : 33
URL      : https://mirrors.kernel.org/gnu/autogen/rel5.18.16/autogen-5.18.16.tar.xz
Source0  : https://mirrors.kernel.org/gnu/autogen/rel5.18.16/autogen-5.18.16.tar.xz
Source1  : https://mirrors.kernel.org/gnu/autogen/rel5.18.16/autogen-5.18.16.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 LGPL-3.0
Requires: autogen-bin = %{version}-%{release}
Requires: autogen-data = %{version}-%{release}
Requires: autogen-lib = %{version}-%{release}
Requires: autogen-license = %{version}-%{release}
Requires: autogen-man = %{version}-%{release}
Requires: guile
BuildRequires : buildreq-configure
BuildRequires : guile-dev
BuildRequires : intltool-dev
BuildRequires : libxml2-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Enable-guile-3.patch
Patch2: 0002-make-man-page-tars-reproducable.patch

%description
This is AutoGen, an automated text file generator.  It was inspired out of
frustration and hassle with maintaining syncronization between option flag
lists, global variables and usage information.  The desire for more than
#define macros came about when it became apparent that macros alone were
insufficient for reducing the maintenance into a single option list.  The
impetus to actually start something finally came when I had to maintain a
large callout procedure table and associated lookup tables.

%package bin
Summary: bin components for the autogen package.
Group: Binaries
Requires: autogen-data = %{version}-%{release}
Requires: autogen-license = %{version}-%{release}

%description bin
bin components for the autogen package.


%package data
Summary: data components for the autogen package.
Group: Data

%description data
data components for the autogen package.


%package dev
Summary: dev components for the autogen package.
Group: Development
Requires: autogen-lib = %{version}-%{release}
Requires: autogen-bin = %{version}-%{release}
Requires: autogen-data = %{version}-%{release}
Provides: autogen-devel = %{version}-%{release}
Requires: autogen = %{version}-%{release}

%description dev
dev components for the autogen package.


%package lib
Summary: lib components for the autogen package.
Group: Libraries
Requires: autogen-data = %{version}-%{release}
Requires: autogen-license = %{version}-%{release}

%description lib
lib components for the autogen package.


%package license
Summary: license components for the autogen package.
Group: Default

%description license
license components for the autogen package.


%package man
Summary: man components for the autogen package.
Group: Default

%description man
man components for the autogen package.


%prep
%setup -q -n autogen-5.18.16
cd %{_builddir}/autogen-5.18.16
%patch -P 1 -p1
%patch -P 2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697058971
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static --disable-dependency-tracking
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1697058971
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/autogen
cp %{_builddir}/autogen-%{version}/COPYING %{buildroot}/usr/share/package-licenses/autogen/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/autogen-%{version}/pkg/libopts/COPYING.gplv3 %{buildroot}/usr/share/package-licenses/autogen/33eb5592147416092b4bad559d7dff2b4186f5f2 || :
cp %{_builddir}/autogen-%{version}/pkg/libopts/COPYING.lgplv3 %{buildroot}/usr/share/package-licenses/autogen/d981a9ec80bd5ecd5f7cf8f53ca8484418b2d8af || :
cp %{_builddir}/autogen-%{version}/pkg/libopts/COPYING.mbsd %{buildroot}/usr/share/package-licenses/autogen/d5a774e469a622f792d89922ece780e651623731 || :
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/autogen/tpl-config.tlib

%files bin
%defattr(-,root,root,-)
/usr/bin/autogen
/usr/bin/autoopts-config
/usr/bin/columns
/usr/bin/getdefs

%files data
%defattr(-,root,root,-)
/usr/share/autogen/Mdoc.pm
/usr/share/autogen/aginfo.tpl
/usr/share/autogen/aginfo3.tpl
/usr/share/autogen/agman-cmd.tpl
/usr/share/autogen/agman-file.tpl
/usr/share/autogen/agman.tlib
/usr/share/autogen/agman1.tpl
/usr/share/autogen/agman3.tpl
/usr/share/autogen/agmdoc-cmd.tpl
/usr/share/autogen/agmdoc-file.tpl
/usr/share/autogen/agpl.lic
/usr/share/autogen/agtexi-cmd.tpl
/usr/share/autogen/agtexi-file.tpl
/usr/share/autogen/autoopts.m4
/usr/share/autogen/bits.tpl
/usr/share/autogen/cmd-doc.tlib
/usr/share/autogen/def2pot.tpl
/usr/share/autogen/fsm-macro.tlib
/usr/share/autogen/fsm-trans.tlib
/usr/share/autogen/fsm.tpl
/usr/share/autogen/getopt.tpl
/usr/share/autogen/gpl.lic
/usr/share/autogen/gplv2.lic
/usr/share/autogen/lgpl.lic
/usr/share/autogen/lgplv2.lic
/usr/share/autogen/libopts-42.1.17.tar.gz
/usr/share/autogen/liboptschk.m4
/usr/share/autogen/man2mdoc
/usr/share/autogen/man2texi
/usr/share/autogen/mbsd.lic
/usr/share/autogen/mdoc2man
/usr/share/autogen/mdoc2texi
/usr/share/autogen/optcode.tlib
/usr/share/autogen/opthead.tlib
/usr/share/autogen/options.tpl
/usr/share/autogen/optlib.tlib
/usr/share/autogen/optmain.tlib
/usr/share/autogen/perlopt.tpl
/usr/share/autogen/rc-sample.tpl
/usr/share/autogen/stdoptions.def
/usr/share/autogen/str2enum.tpl
/usr/share/autogen/str2init.tlib
/usr/share/autogen/str2mask.tpl
/usr/share/autogen/strings.tpl
/usr/share/autogen/texi2man
/usr/share/autogen/texi2mdoc
/usr/share/autogen/tpl-config.tlib
/usr/share/autogen/usage.tlib

%files dev
%defattr(-,root,root,-)
/usr/include/autoopts/options.h
/usr/include/autoopts/usage-txt.h
/usr/lib64/libopts.so
/usr/lib64/pkgconfig/autoopts.pc
/usr/share/aclocal/*.m4
/usr/share/man/man3/ao_string_tokenize.3
/usr/share/man/man3/configFileLoad.3
/usr/share/man/man3/optionFileLoad.3
/usr/share/man/man3/optionFindNextValue.3
/usr/share/man/man3/optionFindValue.3
/usr/share/man/man3/optionFree.3
/usr/share/man/man3/optionGetValue.3
/usr/share/man/man3/optionLoadLine.3
/usr/share/man/man3/optionMemberList.3
/usr/share/man/man3/optionNextValue.3
/usr/share/man/man3/optionOnlyUsage.3
/usr/share/man/man3/optionPrintVersion.3
/usr/share/man/man3/optionPrintVersionAndReturn.3
/usr/share/man/man3/optionProcess.3
/usr/share/man/man3/optionRestore.3
/usr/share/man/man3/optionSaveFile.3
/usr/share/man/man3/optionSaveState.3
/usr/share/man/man3/optionUnloadNested.3
/usr/share/man/man3/optionVersion.3
/usr/share/man/man3/strequate.3
/usr/share/man/man3/streqvcmp.3
/usr/share/man/man3/streqvmap.3
/usr/share/man/man3/strneqvcmp.3
/usr/share/man/man3/strtransform.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopts.so.25
/usr/lib64/libopts.so.25.17.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/autogen/33eb5592147416092b4bad559d7dff2b4186f5f2
/usr/share/package-licenses/autogen/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/autogen/d5a774e469a622f792d89922ece780e651623731
/usr/share/package-licenses/autogen/d981a9ec80bd5ecd5f7cf8f53ca8484418b2d8af

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/autogen.1
/usr/share/man/man1/autoopts-config.1
/usr/share/man/man1/columns.1
/usr/share/man/man1/getdefs.1
